# Generated by Django 3.2.5 on 2021-08-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usertype_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='nep_name',
        ),
    ]
