# Generated by Django 3.2.5 on 2021-08-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_auto_20210820_0801'),
        ('accounts', '0004_auto_20210820_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_status', models.IntegerField(choices=[(1, 'Unpaid'), (2, 'Paid in Cash'), (3, 'Paid in Cheque'), (4, 'Free Distribution')])),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shoppingcart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemcoloravailability')),
            ],
        ),
    ]
