# Generated by Django 3.2.5 on 2021-08-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='paid_status',
            field=models.IntegerField(choices=[(1, 'Unpaid'), (2, 'Paid in Cash'), (3, 'Paid in Cheque'), (4, 'Free Distribution')], default=1),
        ),
    ]
