# Generated by Django 3.2.5 on 2021-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_shoppingcart_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitems',
            name='tax_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingitems',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
