# Generated by Django 3.2.5 on 2021-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210820_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('-paid_status',)},
        ),
        migrations.AlterField(
            model_name='shoppingitems',
            name='price',
            field=models.FloatField(default=0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='shoppingitems',
            name='qty',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
