# Generated by Django 3.2.5 on 2021-08-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_color_hash_code'),
        ('market', '0004_auto_20210824_1639'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingitems',
            unique_together={('cart', 'item')},
        ),
    ]
