# Generated by Django 3.2.5 on 2021-08-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_shoppingitems_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='total_tax',
            field=models.FloatField(default=0.0),
        ),
    ]
