# Generated by Django 3.2.5 on 2021-08-31 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_shoppingcart_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_tax',
        ),
        migrations.RemoveField(
            model_name='shoppingitems',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shoppingitems',
            name='tax_included',
        ),
        migrations.RemoveField(
            model_name='shoppingitems',
            name='taxable',
        ),
    ]
