# Generated by Django 3.2.5 on 2021-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20210831_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitems',
            name='price',
            field=models.FloatField(default=0, verbose_name='Rate'),
        ),
    ]
