# Generated by Django 3.2.5 on 2021-09-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_shoppingitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitems',
            name='tax_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingitems',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
