# Generated by Django 3.2.5 on 2021-08-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dealermeta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DealerMeta',
            new_name='Dealer',
        ),
    ]
