# Generated by Django 3.2.5 on 2021-09-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210901_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_of_type',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Owner')], default=1),
        ),
    ]
