# Generated by Django 3.2.5 on 2021-08-31 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210820_0832'),
        ('market', '0010_auto_20210831_0850'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_posted', models.BooleanField(default=False)),
                ('total', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('paid_amount', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('to_pay', models.FloatField(blank=True, default=0, null=True)),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vat_bill_no', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bill No')),
                ('is_vat', models.BooleanField(default=False)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issued_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.shoppingcart')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('taxable', models.BooleanField()),
                ('tax_include', models.BooleanField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.invoice')),
            ],
        ),
    ]
