# Generated by Django 3.2.5 on 2021-08-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='opening_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_qty', models.FloatField(verbose_name='Opening Quantity')),
                ('rate', models.FloatField(verbose_name='Opening Rate')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
            ],
        ),
    ]
