# Generated by Django 3.2.5 on 2021-08-01 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('inventory', '0002_auto_20210801_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='opening_inventory',
            new_name='openingInventory',
        ),
    ]
