# Generated by Django 3.2.5 on 2021-09-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_itemcoloravailability_unique_together'),
        ('inventory', '0004_alter_openinginventory_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinginventory',
            unique_together={('product',)},
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemcoloravailability')),
            ],
        ),
    ]
