# Generated by Django 3.2.5 on 2021-09-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_itemcoloravailability_unique_together'),
        ('inventory', '0005_auto_20210912_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='count',
            field=models.FloatField(default=0, verbose_name='Existing Qty'),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='rate',
            field=models.FloatField(default=0, verbose_name='Current Rate'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycount',
            unique_together={('product',)},
        ),
    ]
