# Generated by Django 3.2.5 on 2021-09-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20210913_1001'),
        ('inventory', '0007_auto_20210913_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='current_opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.openinginventory'),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='current_purchase_pointer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.purchaseitem'),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='count_updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
