# Generated by Django 3.2.5 on 2021-08-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('taxable', models.BooleanField(default=False)),
                ('taxInc', models.BooleanField(default=True, verbose_name='Included Tax')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
                ('salesInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.salesinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
