# Generated by Django 3.2.5 on 2021-08-01 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_rename_dealermeta_dealer'),
        ('invoice', '0002_salesitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='issued_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.dealer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='expiryDate',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='issued_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='purchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('taxable', models.BooleanField(default=False)),
                ('taxInc', models.BooleanField(default=True, verbose_name='Included Tax')),
                ('expiryDate', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
                ('purchaseInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.purchaseinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
