# Generated by Django 3.2.5 on 2021-09-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_itemcoloravailability_unique_together'),
        ('invoice', '0004_auto_20210801_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='entry_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='entry_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemcoloravailability'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemcoloravailability'),
        ),
    ]
