# Generated by Django 3.2.5 on 2021-09-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20210901_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='rate',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='taxInc',
            new_name='tax_include',
        ),
        migrations.RenameField(
            model_name='salesitem',
            old_name='rate',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='salesitem',
            old_name='taxInc',
            new_name='tax_include',
        ),
    ]
