# Generated by Django 3.2.5 on 2021-08-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag Name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Item Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Product Code')),
                ('tags', models.ManyToManyField(blank=True, to='products.Tags')),
            ],
        ),
    ]
