# Generated by Django 3.2.5 on 2021-08-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210805_1535'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tags',
            constraint=models.UniqueConstraint(fields=('name',), name='unique name'),
        ),
    ]
