# Generated by Django 3.2.5 on 2021-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_itemcoloravailability_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hash_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Color Code'),
        ),
    ]
